name: flutter_learning
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # localization
  slang: ^3.23.0
  slang_flutter: ^3.23.0

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.6
  slide_to_act: ^2.0.1


dev_dependencies:
  slang_build_runner: ^3.23.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true